yaakovGreeter.sayHello();
paulGreeter.sayHello();
frankGreeter.sayHello();
larryGreeter.sayHello();
paulaGreeter.sayHello();
LauraGreeter.sayHello();
johnGoodbye.sayBye();
jamesGoodbye.sayBye();
jimGoodbye.sayBye();